# Generated by Django 4.2.30 on 2026-04-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NepseIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'NEPSE Index',
                'verbose_name_plural': 'NEPSE Indexes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='nepse_data.nepseindex')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='nepse_data.sector')),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('source', models.CharField(max_length=100)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(blank=True, db_column='symbol', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_events', to='nepse_data.stock', to_field='symbol')),
            ],
            options={
                'verbose_name': 'News Event',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv_data', to='nepse_data.stock', to_field='symbol')),
            ],
            options={
                'verbose_name': 'OHLCV',
                'verbose_name_plural': 'OHLCV Records',
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('macd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('macd_hist', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('ema_20', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ema_50', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bb_middle', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='nepse_data.stock', to_field='symbol')),
            ],
            options={
                'verbose_name': 'Technical Indicator',
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
