# Generated by Django 4.2.30 on 2026-04-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0002_indicator_atr_indicator_beta_indicator_obv_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='symbol',
        ),
        migrations.AlterUniqueTogether(
            name='ohlcv',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ohlcv',
            name='symbol',
        ),
        migrations.AlterModelOptions(
            name='newsevent',
            options={'ordering': ['-published_date', '-fetched_at'], 'verbose_name': 'News Event'},
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_events', to='nepse_data.stock', to_field='symbol'),
        ),
        migrations.AddIndex(
            model_name='newsevent',
            index=models.Index(fields=['symbol', 'published_date'], name='nepse_data__symbol__e4db4e_idx'),
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.DeleteModel(
            name='OHLCV',
        ),
    ]
